"""create rss and user model

Revision ID: 7f1928655b08
Revises: 5ff42b83492e
Create Date: 2021-07-02 16:54:44.312588

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7f1928655b08'
down_revision = '5ff42b83492e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss',
    sa.Column('rss_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rss_link', sa.String(length=255), nullable=True),
    sa.Column('rss_title', sa.String(length=255), nullable=True, comment='订阅的标题'),
    sa.Column('rss_subtitle', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('rss_version', sa.String(length=10), nullable=True),
    sa.Column('rss_state', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('rss_id'),
    sa.UniqueConstraint('rss_link')
    )
    op.create_table('rss_content',
    sa.Column('content_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_base', sa.String(length=255), nullable=True),
    sa.Column('content_link', sa.String(length=512), nullable=True),
    sa.Column('content_title', sa.String(length=255), nullable=True),
    sa.Column('content_description', sa.TEXT(), nullable=True),
    sa.Column('content_image_cover', sa.String(length=255), nullable=True),
    sa.Column('published_time', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('rss_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['rss_id'], ['rss.rss_id'], ),
    sa.PrimaryKeyConstraint('content_id'),
    sa.UniqueConstraint('content_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rss_content')
    op.drop_table('rss')
    # ### end Alembic commands ###
