"""create user

Revision ID: 8add65655a23
Revises: 7f1928655b08
Create Date: 2021-07-04 15:56:07.151046

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8add65655a23'
down_revision = '7f1928655b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('permission_scrop', sa.INTEGER(), nullable=False, comment='用户的权限'),
    sa.Column('description', sa.String(length=255), nullable=False, comment='角色的描述'),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
